version: "3.6"
services:
  thehive-db:
    container_name: thehive-db
    hostname: thehive-db
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-thehive}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secret}
      PGDATA: /data/postgres
    volumes:
      - ./docker/postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - thehive_network

networks:
  thehive_network:
    external: true
